### ISSUE TITLE
demo无法运行哟

### ISSUE THREAD

**Issue by YongLeiCHU** [Wuou/WOCrashProtector#1]
如题

**Comment by Wuou** [comment]
报什么错？

**Comment by YongLeiCHU** [comment]
找不到字典的分类




| |
楚永磊
邮箱：yongleichu@163.com
|

签名由 网易邮箱大师 定制

在2018年02月27日 23:11，Wuou 写道：

报什么错？

**Comment by Wuou** [comment]
pch文件重新设置下路径，在setting -> pch 中设置
